server:
  port: 8081
## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring:
  servlet:
    multipart:
      enabled: true
  # Threshold after which files are written to disk.
      file-size-threshold: 2KB
  # Max file size.
      max-file-size: 200MB
  # Max Request Size
      max-request-size: 215MB

      ## File Storage Properties
      # Please change this to the path where you want the uploaded files to be stored.
file:
  upload-dir: storage/decemo