spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: bar-explorer
          uri: http://bar-explorer-service:8080
          predicates:
            - Path=/api/v1/explorer/**
        - id: decemo-user
          uri: http://decemo-user-service:8080
          predicates:
            - Path=/api/v1/user/**
        - id: decemo-reservation
          uri: http://decemo-reservation-service:8080
          predicates:
            - Path=/api/v1/reservation/**