server:
  servlet:
    context-path: "/api/v1/reservation"
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:54320/cdrdb
#    url: jdbc:postgresql://localhost:54320/cdrdb
    username: cdruser
    password: cdrpass
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html

decemo:
  jwt:
    baseUrl: "http://decemo-authorization-service:8080"
#    baseUrl: "http://localhost:8083"
  reservation:
    external:
      clientName: bar
      url: "http://bar-explorer-service:8080"
#      url: "http://localhost:8084"