spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/cdrdb
    username: cdruser
    password: cdrpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html